import type { Framework } from "./types";

// The eleven multi-angle frameworks from the spec. Carousel templates (T1-T9)
// are MVP-ready; video templates (V1-V2) ship as data but are flagged disabled
// until the video phase. On-screen text, captions, hashtags and pro tips are
// transcribed from the spec; layouts/asset slots are inferred from each slide's
// visual cue so the renderer and mixing engine can resolve them.

export const FRAMEWORKS: Framework[] = [
  {
    id: "T1",
    angle: "pain_point",
    name: "The Pain Point / Problem Solver",
    goal: "Name a frustration the audience feels daily, twist the knife, then reveal the app as the relief.",
    bestFor: "Productivity, B2B SaaS, automation, finance, and any tool that removes a recurring chore.",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 6,
    niches: ["app", "ecomm", "personal_brand", "viral"],
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", asset: "hook", text: "POV: you're a [Target_Audience] and it's 11pm and [Core_Problem] AGAIN", visual: "dim, relatable lifestyle shot; bold white text on dark overlay", audio: "trending moody / day-in-the-life sound" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "hook", text: "You've tried everything. Nothing sticks.", visual: "same hook-image family, frustrated mood, text only", audio: "audio builds tension (low hum)" },
      { n: 3, role: "value", layout: "text_only", text: "And it's quietly costing you [Key_Outcome].", visual: "plain dark slide, single line of text centered", audio: "beat drop / pause" },
      { n: 4, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Until I found [App_Name].", visual: "first reveal of the demo sliding in; logo top-left", audio: "audio lifts / uplifting switch" },
      { n: 5, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "[App_Name] does [Feature_Benefit] in seconds.", visual: "clean demo on brand-color background, arrow callout", audio: "bright, confident bed" },
      { n: 6, role: "cta", layout: "text_only", asset: "logo", text: "[CTA_Text] — link in bio · [Handle]", visual: "logo + demo thumbnail; high-contrast button graphic", audio: "audio resolves" },
    ],
    caption: "If you're a [Target_Audience], this one's for you. [Core_Problem] used to wreck my week. Not anymore. [CTA_Text] \u2193",
    hashtags: ["#[App_Category]", "#saas", "#founder"],
    proTip: "The strongest pain-point hooks are oddly specific. \"11pm AGAIN\" beats \"struggling with productivity.\" Let the copy mine [Core_Problem] for a concrete moment.",
  },
  {
    id: "T2",
    angle: "feature_spotlight",
    name: "The Feature Spotlight",
    goal: "Zoom in on ONE feature and make it look magic. Depth beats breadth.",
    bestFor: "Apps with a standout 'wow' feature or a recent launch you want to push.",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 5,
    niches: ["app", "ecomm"],
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", asset: "demo", text: "This [App_Category] feature feels illegal to know.", visual: "demo blurred behind, bold curiosity-gap text", audio: "trending 'wait for it' / reveal sound" },
      { n: 2, role: "value", layout: "split_compare", asset: "demo", text: "Most [Target_Audience] still do [Core_Problem] by hand.", visual: "split: tired hook image | crisp demo", audio: "VO: \"You don't have to.\"" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Meet [Feature_Name].", visual: "hero demo, zoomed on the feature, circle highlight", audio: "beat hit on the word 'Meet'" },
      { n: 4, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "So you [Feature_Benefit] \u2192 [Key_Outcome].", visual: "annotated demo with before\u2192after arrow", audio: "confident bed" },
      { n: 5, role: "cta", layout: "text_only", asset: "logo", text: "[App_Name]. [CTA_Text]. [Handle]", visual: "logo + button graphic on brand color", audio: "resolve" },
    ],
    caption: "[Feature_Name] is the reason I stopped [Core_Problem]. Here's how it works \u2191 [CTA_Text]",
    hashtags: ["#[App_Category]", "#buildinpublic"],
    proTip: "Generate one Feature Spotlight per feature in the Brain profile, then loop demo variants for each. One feature \u00d7 many demo screenshots = many fresh posts.",
  },
  {
    id: "T3",
    angle: "competitor_callout",
    name: "The Competitor Call-Out",
    goal: "Position the app against the old / clunky way. Comparison drives clarity and identity.",
    bestFor: "Crowded categories where differentiation is the whole battle.",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 5,
    niches: ["app", "ecomm"],
    slides: [
      { n: 1, role: "hook", layout: "split_compare", asset: "demo", text: "[Competitor_Name] vs [App_Name]: it's not close.", visual: "split screen, two logos / two demos facing off", audio: "trending 'versus' / boxing-bell sound" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "With [Competitor_Name] you still [Competitor_Weakness].", visual: "greyed, dull demo of the 'old way'; red X", audio: "VO: deadpan" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "[App_Name] just [Feature_Benefit].", visual: "bright demo, green check, brand-color frame", audio: "upbeat switch" },
      { n: 4, role: "value", layout: "text_only", text: "Speed \u2713 Price \u2713 [Value_Prop_1] \u2713", visual: "comparison table graphic: us vs them", audio: "tick sounds per check" },
      { n: 5, role: "cta", layout: "text_only", asset: "logo", text: "Switch in 2 minutes \u2192 [CTA_Text]. [Handle]", visual: "logo + button; 'Make the switch' banner", audio: "resolve" },
    ],
    caption: "I switched from [Competitor_Name] and never looked back. The difference \u2191 [CTA_Text]",
    hashtags: ["#[App_Category]", "#comparison"],
    proTip: "If naming a real competitor feels risky, set [Competitor_Name] = \"the old way\" or \"spreadsheets.\" Same psychology, zero legal friction.",
  },
  {
    id: "T4",
    angle: "how_to",
    name: "The How-To Tutorial",
    goal: "Teach a quick win using the app. Educational saves and shares; the product is the hero of the method.",
    bestFor: "Tools with a clear workflow; great for SEO-style 'how to X' discovery.",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 6,
    niches: ["app", "ecomm", "personal_brand", "viral"],
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", asset: "demo", text: "How to [Key_Outcome] in under 60 seconds", visual: "demo preview, numbered '1\u00b72\u00b73' graphic", audio: "calm, tutorial-style trending audio" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "1. Open [App_Name] and [first action].", visual: "demo step 1, finger-tap cursor, step badge", audio: "VO narrates each tap" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "2. [second action] — it auto-[Feature_Benefit].", visual: "demo step 2, highlight box", audio: "VO continues" },
      { n: 4, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "3. Done. [Key_Outcome] \u2713", visual: "demo result screen, confetti accent", audio: "success chime" },
      { n: 5, role: "value", layout: "fullbleed_dark_overlay", asset: "hook", text: "That's it. No [Core_Problem], no fuss.", visual: "relaxed lifestyle hook shot", audio: "warm bed" },
      { n: 6, role: "cta", layout: "text_only", asset: "logo", text: "Save this. Then [CTA_Text]. [Handle]", visual: "logo + bookmark icon prompt", audio: "resolve" },
    ],
    caption: "The 60-second way to [Key_Outcome]. Save it for later [CTA_Text]",
    hashtags: ["#howto", "#[App_Category]", "#tutorial"],
    proTip: "Tutorials are the best save-magnets. Always include an explicit \"Save this\" prompt — saves are weighted heavily by the algorithm.",
  },
  {
    id: "T5",
    angle: "social_proof",
    name: "The Social Proof / Review",
    goal: "Let users do the selling. Testimonials, ratings, and results build trust faster than claims.",
    bestFor: "Apps with happy users, reviews, or measurable wins to show off.",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 5,
    niches: ["app", "ecomm", "personal_brand"],
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", asset: "hook", text: "[Metric_Result]. Here's what people are saying about [App_Name] \u2193", visual: "5-star graphic over soft hook image", audio: "trending warm / wholesome sound" },
      { n: 2, role: "value", layout: "testimonial_card", text: "\u201c[User_Quote]\u201d — [User_Name], [User_Title]", visual: "testimonial card UI, avatar, 5 stars", audio: "VO reads the quote" },
      { n: 3, role: "value", layout: "testimonial_card", text: "\u201c[User_Quote_2]\u201d", visual: "second styled review card, different color", audio: "VO continues" },
      { n: 4, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Average user: [Metric_Result].", visual: "demo with a stat callout overlay", audio: "confident bed" },
      { n: 5, role: "cta", layout: "text_only", asset: "logo", text: "Join them \u2192 [CTA_Text]. [Handle]", visual: "logo + grid of avatars graphic", audio: "resolve" },
    ],
    caption: "Real reviews, real results. [Metric_Result] and counting [CTA_Text]",
    hashtags: ["#testimonial", "#[App_Category]"],
    proTip: "Style each review as a fake-native UI card (iMessage, app-store review, tweet). Familiar UI shells out-perform plain quote text.",
  },
  {
    id: "T6",
    angle: "before_after",
    name: "The Before / After Transformation",
    goal: "Show the messy 'before' and the clean 'after.' Pure visual contrast — the format does the persuading.",
    bestFor: "Visual apps: design, photo/video, makeup, food, dashboards, before/after data.",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 4,
    niches: ["ecomm", "app", "personal_brand", "viral"],
    slides: [
      { n: 1, role: "hook", layout: "split_compare", text: "Before [App_Name] \u2192 After [App_Name]", visual: "split: before hook image | after demo", audio: "trending 'glow-up' / transformation sound" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "hook", text: "This was my [Core_Problem]\u2026", visual: "full-bleed messy 'before' hook image, muted tones", audio: "audio low / unresolved" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "\u2026and this is 30 seconds with [App_Name].", visual: "full-bleed polished 'after' demo, vivid", audio: "beat drop on reveal" },
      { n: 4, role: "cta", layout: "text_only", asset: "logo", text: "Your turn. [CTA_Text]. [Handle]", visual: "side-by-side thumbnail + logo + button", audio: "resolve" },
    ],
    caption: "The before/after still gets me [CTA_Text] and try it on yours",
    hashtags: ["#beforeandafter", "#[App_Category]", "#glowup"],
    proTip: "This is the highest-velocity template for the Mixing engine: every hook (before) \u00d7 every demo (after) is a unique, instantly-postable pair.",
  },
  {
    id: "T7",
    angle: "story_hook",
    name: "The Story Hook / Swipe-Bait",
    goal: "A text-led story or list so intriguing people swipe to finish it. Minimal design, maximum curiosity.",
    bestFor: "Building reach / top-of-funnel awareness; works for any [App_Category].",
    format: "carousel",
    ratios: ["4:5", "9:16"],
    slideCount: 5,
    niches: ["personal_brand", "viral", "app"],
    slides: [
      { n: 1, role: "hook", layout: "text_only", text: "I grew my [thing] to [number] using one [App_Category]. Here's the exact playbook:", visual: "plain brand-color slide, big bold text, tiny 'swipe \u2192'", audio: "trending storytime / lo-fi bed" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "hook", text: "6 months ago I was stuck with [Core_Problem].", visual: "text-only slide, subtle hook-image texture", audio: "VO storytime cadence" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Then I started using [App_Name] for [Feature_Name].", visual: "first demo peek", audio: "continues" },
      { n: 4, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Result: [Key_Outcome]. No joke.", visual: "demo with stat callout", audio: "slight lift" },
      { n: 5, role: "cta", layout: "text_only", asset: "logo", text: "I put the link in bio. [CTA_Text]. [Handle]", visual: "logo + soft button", audio: "resolve" },
    ],
    caption: "The full playbook is in the slides \u2191 took me 6 months to learn, 60 seconds to read. [CTA_Text]",
    hashtags: ["#storytime", "#[App_Category]"],
    proTip: "Keep slide 1 text-only and benefit-loaded — no product yet. Curiosity, not the logo, earns the first swipe. Introduce [App_Name] no earlier than slide 3.",
  },
  {
    id: "T8",
    angle: "meme",
    name: "The Meme / Relatable",
    goal: "One funny, relatable image with a caption overlay. Cheap to make, high shareability.",
    bestFor: "Awareness, community building, and humanizing the brand. Low-lift, high-volume.",
    format: "single_image",
    ratios: ["4:5", "9:16"],
    slideCount: 3,
    niches: ["viral", "personal_brand"],
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", asset: "hook", text: "[Target_Audience] trying to handle [Core_Problem] without [App_Name]:", visual: "expressive/funny hook shot, classic meme text top+bottom", audio: "trending meme audio of the week" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Meanwhile, me with [App_Name]:", visual: "calm 'it just works' demo contrast shot", audio: "audio punchline beat" },
      { n: 3, role: "cta", layout: "text_only", asset: "logo", text: "ok but seriously \u2192 [Handle]", visual: "logo small, low-key text", audio: "tail of the sound" },
    ],
    caption: "if you know, you know [Handle]",
    hashtags: ["#relatable", "#[App_Category]", "#meme"],
    proTip: "Memes should sell only ~10%. Keep the product almost incidental — over-branding kills the share. Pull humor from the [Brand_Voice] descriptor.",
  },
  {
    id: "T9",
    angle: "emotional_trigger",
    name: "The Emotional Trigger (Fake DM / Notification)",
    goal: "Mimic a personal message, DM, or notification so it stops the scroll like real content.",
    bestFor: "Curiosity-driven reach; works especially well for community / social / creator apps.",
    format: "single_image",
    ratios: ["4:5", "9:16"],
    slideCount: 2,
    niches: ["viral", "personal_brand", "app"],
    slides: [
      { n: 1, role: "hook", layout: "notification_mock", asset: "hook", text: "Notification: \u201c[User_Quote]\u201d", visual: "native-looking iMessage / push-notification UI mock over a blurred hook image", audio: "notification 'ding' + trending emotional sound" },
      { n: 2, role: "cta", layout: "fullbleed_dark_overlay", asset: "demo", text: "\u2026this is what [App_Name] does for [Target_Audience].", visual: "demo reveal + logo; soft CTA [Handle]", audio: "warm resolve" },
    ],
    caption: "got this and had to share [Handle]",
    hashtags: ["#[App_Category]"],
    proTip: "Authenticity is everything — render the notification UI pixel-accurate. The instant it looks like an ad, the scroll-stop effect dies.",
  },
  {
    id: "V1",
    angle: "ai_avatar_hook",
    name: "The AI Avatar Hook (UGC Talking-Head)",
    goal: "An AI presenter delivers a spoken hook, then cuts to a demo. The UGC format that scales testimonials.",
    bestFor: "Video phase. Highest trust + conversion format once video infra ships.",
    format: "video",
    ratios: ["9:16"],
    slideCount: 5,
    niches: ["app", "ecomm", "personal_brand", "viral"],
    disabled: true,
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", text: "Stop [Core_Problem]. Watch this.", visual: "avatar talking head, direct to camera, captions burned in", audio: "VO punchy, native delivery" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "hook", text: "Every [Target_Audience] wastes hours on this\u2026", visual: "avatar continues; b-roll hook cutaway", audio: "same VO, conversational" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "\u2026here's how [App_Name] fixes it.", visual: "cut to demo screen recording, zoomed taps", audio: "VO narrates the demo" },
      { n: 4, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "[Key_Outcome] \u2713", visual: "demo result + animated caption", audio: "energy peak" },
      { n: 5, role: "cta", layout: "text_only", asset: "logo", text: "[CTA_Text] — link in bio.", visual: "avatar sign-off + logo end-card + [Handle]", audio: "VO resolve + button SFX" },
    ],
    caption: "POV: you found the [App_Category] that does it for you [CTA_Text]",
    hashtags: ["#ugc", "#[App_Category]", "#fyp"],
    proTip: "Generate 3–5 VO-script variants per video and rotate avatar presenters. Same structure, fresh face + hook = dozens of testable variants.",
  },
  {
    id: "V2",
    angle: "screen_recording",
    name: "The Screen-Recording Walkthrough",
    goal: "Fast, satisfying tour of the app doing the thing. The product is the star; captions carry the story.",
    bestFor: "Video phase. Best for demonstrating a slick UI or an automation 'wow' moment.",
    format: "video",
    ratios: ["9:16"],
    slideCount: 4,
    niches: ["app", "ecomm"],
    disabled: true,
    slides: [
      { n: 1, role: "hook", layout: "fullbleed_dark_overlay", asset: "demo", text: "Watch [App_Name] do [Key_Outcome] \u2193", visual: "cold-open straight into demo, zoomed, fast", audio: "trending 'oddly satisfying' audio" },
      { n: 2, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "Animated captions label each tap & result.", visual: "demo screen recording, speed-ramped, cursor highlights", audio: "audio synced to taps" },
      { n: 3, role: "value", layout: "fullbleed_dark_overlay", asset: "demo", text: "[Feature_Benefit] \u2192 [Key_Outcome]", visual: "demo final result screen, zoom + freeze", audio: "beat hit" },
      { n: 4, role: "cta", layout: "text_only", asset: "logo", text: "[CTA_Text]. [Handle]", visual: "logo end-card + button graphic", audio: "resolve" },
    ],
    caption: "this is so satisfying to watch [CTA_Text]",
    hashtags: ["#[App_Category]", "#saas", "#satisfying"],
    proTip: "Speed-ramp the boring parts and slow down on the 'wow' moment. Auto-generated captions should sync to each on-screen action.",
  },
];
