import type { NicheSlug } from "@/lib/carousel/niches";

/** Seed template definition used by migration + carousel slide generator. */
export interface SeedTemplateDef {
  id: string;
  slug: string;
  title: string;
  description: string;
  niche: NicheSlug;
  author_name: string;
  upvote_count: number;
  downvote_count: number;
  download_count: number;
  /** Tailwind-style gradient stops for SVG backgrounds. */
  gradientFrom: string;
  gradientTo: string;
  slideLabels: string[];
}

export const SEED_TEMPLATES: SeedTemplateDef[] = [
  {
    id: "a1000001-0000-4000-8000-000000000001",
    slug: "pov-discovered",
    title: "POV: You Just Discovered This",
    description:
      "POV hook carousel — immersive first-person opener built to earn swipes.",
    niche: "viral",
    author_name: "@creatorhub",
    upvote_count: 847,
    downvote_count: 23,
    download_count: 312,
    gradientFrom: "#34d399",
    gradientTo: "#0d9488",
    slideLabels: [
      "POV: you finally crack the hook formula everyone gatekeeps",
      "You've posted 47 times. Still stuck at 200 views.",
      "Slide 1 decides if anyone swipes",
      "Pattern interrupt + one clear promise = people stay",
      "Save this before your next post",
      "Follow for the full swipe script →",
    ],
  },
  {
    id: "a1000002-0000-4000-8000-000000000002",
    slug: "five-lessons",
    title: "5 Lessons I Wish I Knew Sooner",
    description: "Numbered listicle carousel — one lesson per slide, save-bait CTA.",
    niche: "personal_brand",
    author_name: "Maya K.",
    upvote_count: 612,
    downvote_count: 41,
    download_count: 278,
    gradientFrom: "#a78bfa",
    gradientTo: "#c026d3",
    slideLabels: [
      "5 lessons I wish I knew before building an audience",
      "Lesson 1 — Start before you feel ready",
      "Lesson 2 — Consistency beats talent every time",
      "Lesson 3 — Your niche finds you when you ship",
      "Lesson 4 — Document the process, don't wait for perfect",
      "Lesson 5 — Ship ugly. Refine in public.",
      "Save + follow for weekly scripts",
    ],
  },
  {
    id: "a1000003-0000-4000-8000-000000000003",
    slug: "myth-vs-reality",
    title: "Myth vs Reality",
    description: "Myth vs Reality split-screen carousel — high save rate format.",
    niche: "viral",
    author_name: "@growthlab",
    upvote_count: 534,
    downvote_count: 67,
    download_count: 201,
    gradientFrom: "#fbbf24",
    gradientTo: "#ea580c",
    slideLabels: [
      "MYTH vs REALITY (save this)",
      "MYTH: You need 10K followers to monetize",
      "REALITY: You need 10 people who'd pay tomorrow",
      "MYTH: Post every single day",
      "REALITY: Post when you have something worth saving",
    ],
  },
  {
    id: "a1000004-0000-4000-8000-000000000004",
    slug: "before-after",
    title: "Before → After Transformation",
    description: "Before → After transformation arc for product and brand stories.",
    niche: "ecomm",
    author_name: "@shopflow",
    upvote_count: 421,
    downvote_count: 18,
    download_count: 189,
    gradientFrom: "#fb923c",
    gradientTo: "#e11d48",
    slideLabels: [
      "BEFORE → AFTER — Same product. Different story.",
      "BEFORE: Feature list. Zero emotion.",
      "We tried: specs, discounts, influencer unboxings",
      "Then we led with the transformation customers want",
      "AFTER: Problem → result in 5 slides. 3× save rate",
      "Steal this arc for your next drop →",
    ],
  },
  {
    id: "a1000005-0000-4000-8000-000000000005",
    slug: "step-by-step",
    title: "Step-by-Step Tutorial (1/7)",
    description: "Step-by-step tutorial carousel with numbered cards and progress dots.",
    niche: "app",
    author_name: "DevTips Daily",
    upvote_count: 389,
    downvote_count: 29,
    download_count: 156,
    gradientFrom: "#38bdf8",
    gradientTo: "#4f46e5",
    slideLabels: [
      "How to launch a carousel that actually converts",
      "Step 1 — Pick one painful problem your buyer googles",
      "Step 2 — Write slide 1 like a headline, not a title card",
      "Step 3 — One idea per slide. No paragraphs.",
      "Step 4 — Use contrast: big number or bold claim",
      "Step 5 — End with save CTA + one comment hook",
      "Step 6 — Repurpose top slide as a Reel hook",
      "Step 7 — Track saves, not likes →",
    ],
  },
  {
    id: "a1000006-0000-4000-8000-000000000006",
    slug: "red-green-flags",
    title: "Red Flags / Green Flags",
    description: "Red flag / green flag hook audit — viral comparison format.",
    niche: "viral",
    author_name: "@viralvault",
    upvote_count: 712,
    downvote_count: 89,
    download_count: 445,
    gradientFrom: "#4ade80",
    gradientTo: "#059669",
    slideLabels: [
      "Red flags 🚩 vs Green flags ✅ in your hooks",
      "🚩 Starts with Hey guys welcome back",
      "✅ Opens with a specific painful moment",
      "🚩 No reason to swipe to slide 2",
      "✅ Slide 1 promises a payoff by slide 5",
      "Save this checklist before you post",
    ],
  },
  {
    id: "a1000007-0000-4000-8000-000000000007",
    slug: "hot-take",
    title: "Hot Take Nobody Talks About",
    description: "Contrarian hot take carousel — built to spark comments and shares.",
    niche: "personal_brand",
    author_name: "Jordan Lee",
    upvote_count: 298,
    downvote_count: 112,
    download_count: 134,
    gradientFrom: "#f472b6",
    gradientTo: "#9333ea",
    slideLabels: [
      "Hot take: your carousel isn't flopping because of timing",
      "Everyone says: post at 7am, use 30 hashtags",
      "The data says: slide 1 clarity beats everything",
      "If slide 2 doesn't pay off slide 1's promise, they're gone",
      "Agree or disagree? Comment 👇",
    ],
  },
  {
    id: "a1000008-0000-4000-8000-000000000008",
    slug: "framework",
    title: "The Framework That Changed Everything",
    description: "D.R.I.P. framework carousel — proprietary model for thought leadership.",
    niche: "app",
    author_name: "@saasstudio",
    upvote_count: 445,
    downvote_count: 31,
    download_count: 198,
    gradientFrom: "#60a5fa",
    gradientTo: "#2563eb",
    slideLabels: [
      "The D.R.I.P. framework for carousels that get saved",
      "D — Disrupt: pattern break on slide 1",
      "R — Relate: name their exact pain",
      "I — Inform: give 3–5 sharp steps",
      "P — Push: one CTA — save or DM",
      "Use this on every educational post",
      "Screenshot slide 3 for your next draft →",
    ],
  },
  {
    id: "a1000009-0000-4000-8000-000000000009",
    slug: "us-vs-them",
    title: "Us vs Them Comparison",
    description: "Them vs Us split carousel — product positioning that drives saves.",
    niche: "ecomm",
    author_name: "@brandcompare",
    upvote_count: 267,
    downvote_count: 22,
    download_count: 98,
    gradientFrom: "#fdba74",
    gradientTo: "#dc2626",
    slideLabels: [
      "THEM vs US — why saves differ",
      "THEM ❌ Wall of text on slide 1",
      "US ✅ One bold claim + visual proof",
      "Same offer. Different packaging. Different shares.",
      "Try the US format on your next launch →",
    ],
  },
  {
    id: "a1000010-0000-4000-8000-000000000010",
    slug: "save-checklist",
    title: "Save This Checklist",
    description: "Pre-publish checklist carousel — bookmark bait with 8 audit items.",
    niche: "viral",
    author_name: "@saveworthy",
    upvote_count: 923,
    downvote_count: 45,
    download_count: 567,
    gradientFrom: "#2dd4bf",
    gradientTo: "#0891b2",
    slideLabels: [
      "Save this checklist 📌 Before you publish your next carousel",
      "☐ Hook promises a specific outcome",
      "☐ Each slide earns the next swipe",
      "☐ One stat or proof by slide 3",
      "☐ Text readable on mobile",
      "☐ CTA tells them exactly what to do",
      "☐ Repurpose slide 1 as Reel cover",
      "Done? Post it. Track saves for 48h.",
    ],
  },
  {
    id: "a1000011-0000-4000-8000-000000000011",
    slug: "pas-framework",
    title: "Problem → Agitate → Solution",
    description: "Problem → Agitate → Solution copy arc adapted for 6-slide carousels.",
    niche: "personal_brand",
    author_name: "Copy Coach Ana",
    upvote_count: 356,
    downvote_count: 28,
    download_count: 167,
    gradientFrom: "#c084fc",
    gradientTo: "#7c3aed",
    slideLabels: [
      "Sound familiar? High clicks. Zero saves.",
      "THE PROBLEM: Your carousel teaches nothing worth bookmarking",
      "So the algorithm shows it once and kills reach",
      "Every flop post trains the feed to ignore you",
      "THE FIX: Problem → steps → save CTA in 6 slides",
      "Start with slide 1 rewrite today →",
    ],
  },
  {
    id: "a1000012-0000-4000-8000-000000000012",
    slug: "feature-walkthrough",
    title: "Feature Walkthrough Carousel",
    description: "SaaS product demo carousel — pain → feature → proof → CTA structure.",
    niche: "app",
    author_name: "ProductPulse",
    upvote_count: 198,
    downvote_count: 15,
    download_count: 89,
    gradientFrom: "#7dd3fc",
    gradientTo: "#0284c7",
    slideLabels: [
      "Stop explaining your product in one static image",
      "Slide 2: Show the pain in 8 words max",
      "Slide 3–5: One feature = one outcome",
      "Slide 6: Social proof or metric",
      "Slide 7: Free trial / demo CTA",
      "Carousels beat single images for SaaS demos",
      "Copy this structure for your launch →",
    ],
  },
];

export function seedSlidesJson(slug: string, count: number) {
  return Array.from({ length: count }, (_, i) => ({
    position: i + 1,
    image_url: `/community-templates/${slug}/slide-${i + 1}.jpg`,
    storage_path: "",
    media_type: "image" as const,
  }));
}
